### ISSUE TITLE
Better Colors makes loading old messages insanely slow.

### ISSUE THREAD

**Issue by GenesisAria** [rauenzi/BetterDiscordAddons#10]
I love the all-in-one idea, and it looks real nice, especially with the coloured @mentions, but the slowness it causes is unbearable.

Also, the colours don't always register correctly, and some people it doesn't show up for typing or anything.  There are other plugins that did the colour for typing and for voice yet extremely lightweight.

**Comment by rauenzi** [comment]
@GenesisAria Not sure if you've tried the recent update but most users were reporting a huge speedup for the new method. If the lag still exists, you can temporarily disable mentions as that is the slowest part (but also one of the coolest). The next update my beta testers have reported about a 50% speedup from the update here on github which was already faster.

When do the colors not register correctly? As of now it won't work when the channel members is hidden or if a user is offline (usually). That should hopefully be fixed soon. Aside from those times it should be much more reliable than the original ColoredTyping/Voice by Anxeal (and the fixed version I have on my github) because it goes my user's IDs and not their nicknames which can change and can be stored improperly (due to characters not being escaped).

**Comment by rauenzi** [comment]
If you want to test the beta, feel free to join my server or message me on discord

**Comment by GenesisAria** [comment]
The mentions not being coloured seemed random, i didn't pin down a cause, perhaps they were on mobile thus offline but pop in to check... I wouldn't know.

The colour issue was that some users would show colour and others wouldn't.  When a member's colour didn't register, it didn't do it anywhere: typing, mentions etc.  Oh lol, i actually didn't realize it was yours. Coloured Typing works with the colour always, but this version some people it didn't grab the colour properly.  What's the difference in colour grabbing method?

**Comment by rauenzi** [comment]
Mentions are a known issue with being colored/uncolored because of the way discord organizes them. I'm still working on a solution for that.

Oddly enough, I haven't had anyone else report issues with people not being colored. But either way I have been working on trying to make it even more accurate. If you want to test this version that I've been working on, please let me know.

As a side note ColoredTyping/Voice as I said above was actually by Anxeal I just fixed it/brought it up to date as Anxeal discontinued working on plugins.

**Comment by rauenzi** [comment]
The newest version has a new mention coloring method which appears to be much faster for me, please let me know if it is still insanely slow.

**Comment by GenesisAria** [comment]
Nope, seems to be loading normally now (not fast, but not different than without). Cheers
