### ISSUE TITLE
[Bug] RadialStatus broken after update

### ISSUE THREAD

**Issue by ymmit64** [rauenzi/BetterDiscordAddons#149]
After the latest update where they include the green phone status icon, the radial status code no longer overrides it.
![image](https://user-images.githubusercontent.com/14102998/61752845-4f07ba80-ad7b-11e9-9a02-e905515ad98a.png)

**Comment by wefalltomorrow** [comment]
Not working for me at all now.

**Comment by NoireBlackHeart** [comment]
Hello rauenzi
The thing is, after the released update some CSS and JS files stopped working due to changes in div, style and class elements so I wanted to restore the RadialStatus, but because of the update, everything changed and I could not create a copy of RadialStatus. Most of all I do not like in this update is foreignObject.
Can you tell me how to recreate it?
or a bit of this code.
![image](https://user-images.githubusercontent.com/44205353/64386238-40cae080-d041-11e9-912c-c45db1d2301c.png)
Like i said before i tried to create it but i could not succeed.

**Comment by NoireBlackHeart** [comment]
![image](https://user-images.githubusercontent.com/44205353/64386479-eaaa6d00-d041-11e9-873e-1eb1ed8bbcfe.png)
I’ve already roughly created a preset but I don’t remember / don’t know how to create an additional element to give it a circle shape and apply a border-radius: 0

**Comment by NoireBlackHeart** [comment]
I roughly understand the principle of new code building, but as I said I don’t know how to create a separate element

**Comment by NoireBlackHeart** [comment]
And again, I ask, can you tell me how to create a separate element, etc.?

**Comment by Gibbu** [comment]
I have gotten Zerebos' permission to host my temporary RadialStatus until he updates his.
The only downside to this version is, the avatar and status border is always going to be circle. Due to the restrictions on the avatar structure.

Download: https://betterdiscord.net/ghdl?id=2950
Source: https://github.com/Gibbu/BetterDiscord-Themes/tree/master/RadialStatus

**Comment by NoireBlackHeart** [comment]
Thank you, Gibbu

**Comment by NoireBlackHeart** [comment]
You said "The avatar and status border is always going to be circle" but there is a way to make the avatar square:
#app-mount .wrapper-3t9DeA img {
    border-radius: -10%;
}
![image](https://user-images.githubusercontent.com/44205353/64437081-428eb580-d0ce-11e9-9c35-f41a0ea764fb.png)

**Comment by NoireBlackHeart** [comment]
But I do not really understand how to do the same with status

**Comment by NoireBlackHeart** [comment]
Ignore the code above, I just experimented

**Comment by NoireBlackHeart** [comment]
By the way, can you tell me where I need to put the base.css?

**Comment by Gibbu** [comment]
You shouldn't have to put the base.css anywhere you can just overwrite the rules inside the `RadialStatus.theme.css`. And you can contact me on Discord: Gibbu#1211 or you could just look for my name on the BetterDiscord Servers members list

**Comment by NoireBlackHeart** [comment]
https://media.discordapp.net/attachments/398111271842742292/619862334109646848/unknown.png
)))
