### ISSUE TITLE
[Bug] AccountDetailsPlus wrong positioning

### ISSUE THREAD

**Issue by dcrime** [rauenzi/BetterDiscordAddons#182]
**Which plugin/theme is this about?**
AccountDetailsPlus

**Describe the Bug**
Wrong user menu placement
Status menu and user menu both show up (including Stable)

**To Reproduce**
User Popout - Avatar - Enable
Everything else is disabled

Clicking on the avatar brings up the user menu at the right place but offsets the status menu
Moving the mouse removes the user menu and shows the status menu
Clicking on the avatar again moves everything above the right spot

**Expected Behavior**
A user menu showing up instead of the status menu at the expected place

**Screenshots**
https://i.gyazo.com/72664847686b9822c57acf0b0894516b.png

**Discord Version**
PTB

**Comment by shinji257** [comment]
I've noticed this but also that it seems that both the status change and the account details plus dialogs are both being triggered on click.  When I set it so that only Username is enabled (status doesn't come up there by default) it still triggers both dialogs and I still end up hitting the status change box.  All other options are disabled during this test.

**Comment by Lucasamiel0406** [comment]
Also happens with Stable

**Comment by rauenzi** [comment]
This was fixed.
