### ISSUE TITLE
[Feature][RoleMembers] Show offline members

### ISSUE THREAD

**Issue by jokercardsof0** [rauenzi/BetterDiscordAddons#208]
Allow it to show offline, players as well in the role search.

**Comment by rauenzi** [comment]
This has the unfortunate side effect of forcing Discord to attempt to load all members from the API. This has consequences because it affects the API, and also has consequences because the amount of data loaded in on large servers can cause slowdowns. In the plugin in particular, with large servers if all members are available the plugin will lag or freeze when attempting to show large lists especially `@everyone`.

**Comment by Divoret** [comment]
Hi,

To what you said above, there is an easy fix to this.

Let's say for example, someone wants to see who all has the role "trusted". By default, rolemembers currently shows only online members. 

Add a feature for the offline member part as well. And as for if there are too many offline members? Easy! There is one simple fix.

All you have to do is add a limit to how many offline members it can view or load (can be cuztomized in the config). So it doesn't load all offline members.

Personally, I am in a test server where not many people have a certain role I am looking for. So It would be useful to also add offline member view list, but at a set limit. You could also set it so that a user can manually load some more offline users of a specific role, and if the memory gets a little bit high, the plugin will automatically, clear the previous name cache or data it has collected, to save up space or something like that, maybe.

Let me know what you think

**Comment by rauenzi** [comment]
This is not a feature that I intend to add.
