### ISSUE TITLE
[Bug] BetterRoleColors shows wrong color when mentioning someone but not in the textarea

### ISSUE THREAD

**Issue by puyoxyz** [rauenzi/BetterDiscordAddons#397]
**Which plugin/theme is this about?**
BetterRoleColors

**Describe the Bug**
If you mention someone, the color in the actual message is the default one, not their role color.

It works fine in the textarea but not in the actual message.

![image](https://user-images.githubusercontent.com/15311104/118934947-3c487780-b94b-11eb-9566-73f7abe96ba8.png) 

**Expected Behavior**
Mention color should be the role color.

**Discord Version**
Stable

**Comment by Traktool** [comment]
Not only for invisible role
It's for all roles
![image](https://user-images.githubusercontent.com/22771674/118986298-851a2380-b97f-11eb-8905-ae540d090c79.png)
![image](https://user-images.githubusercontent.com/22771674/118986330-8e0af500-b97f-11eb-8c56-b6a762dbac65.png)

**Comment by Phyronian** [comment]
Can confirm the mention issue.  User has colored roles, however their mentions display as the normal discord would display them; does not reflect their roles.
![image](https://user-images.githubusercontent.com/59706828/119023984-3614c400-b968-11eb-916c-2ef67645864c.png)
![image](https://user-images.githubusercontent.com/59706828/119024004-3ca33b80-b968-11eb-9e72-2abd5e0d1897.png)

**Comment by asportnoy** [comment]
Same here, works fine in the textarea though.
![image](https://user-images.githubusercontent.com/14863373/119041359-269f7600-b97c-11eb-9354-ae976a4088bf.png)

**Comment by rauenzi** [comment]
This has been fixed at the latest version.

**Comment by MysticMismagius** [comment]
Reviving this because it has been happening to me as well.

I have tried:

- Checking the "Use Important" setting in the BetterRoleColors Plugin Settings
- Turning off all themes and unrelated plugins to ensure that the issue was not an incompatibility with one of them
- Deleting and reinstalling the BetterRoleColors Plugin
- Deleting and reinstalling Better Discord
- Deleting and reinstalling Discord itself, then deleting and reinstalling Better Discord again
