### ISSUE TITLE
[Bug] PermissionViewer

### ISSUE THREAD

**Issue by minhngoc25a** [rauenzi/BetterDiscordAddons#418]
**Describe the bug**
The 'Permission' button isn't shown in the drop-down box when a channel is right-clicked. The plugin still functions as intended when I click on server icons, categories, and users. 

**Screenshots**
![image](https://user-images.githubusercontent.com/33834488/122366186-868e3a00-cf85-11eb-8148-2f5b29f4112c.png)
Right-clicking on a channel.
![image](https://user-images.githubusercontent.com/33834488/122366317-a32a7200-cf85-11eb-9aff-8d7ce241689b.png)
Right-clicking on a category.

**Discord Build (stable, ptb or canary):**
Stable.

**Comment by Yokothecat1** [comment]
This issue seems to only be for text channels, but for some reason works as intended for voice channels.
![image](https://user-images.githubusercontent.com/73169855/122678493-d2441c00-d1ef-11eb-8c78-24d593465c06.png)
![image](https://user-images.githubusercontent.com/73169855/122678502-dec87480-d1ef-11eb-97de-42b2a9318389.png)

**Comment by Osyruu** [comment]
#411
