### ISSUE TITLE
[Other] AccountDetailsPlus requires manual restart if used with PinDMs by DevilBro

### ISSUE THREAD

**Issue by Tracenji** [rauenzi/BetterDiscordAddons#419]
if PinDMs is used at the same time then AccountDetailsPlus needs a manual restart every time Discord is loaded

i do not know if this is something that could be fixed or have a workaround on AccountDetailsPlus' side but i wanted to report this incompatibility anyway

**Comment by QbDesu** [comment]
That's a known issue. It's the same with a bunch of plugins probaby. Another known plugin is SpoitfyControls.
https://github.com/rauenzi/BetterDiscordAddons/issues/369

Technical explaination:
The issue is that it only adds the event handers and applies the changes to the avatar+username once when starting up (or when changing a setting too). Any plugin that causes the sidebar or the panel to rerender - which is a resonable thing to do when patching things there - will break ADP because it causes the existing elements to be replaced with new ones, these in turn won't have the changes.
One possible solution is detect the rerendering using the `observer` method and reapply the changes..

**Comment by rauenzi** [comment]
This *should* be fixed at the latest version.
