### ISSUE TITLE
[Bug] PermissionsViewer crash when right click role

### ISSUE THREAD

**Issue by NBDSunsetYT** [rauenzi/BetterDiscordAddons#499]
**Which plugin/theme is this about?**
 Permissions Viewer

**Describe the Bug**
 When you right click a role while viewing permissions discord craashes

**To Reproduce**
  Right click a server click permissions than right click on one of the roles

**Expected Behavior**
 Not supposed to do anything

**Screenshots**
 https://gyazo.com/84eb83dbbce7f60ab144b1f1d9b2375f

**Discord Version**
 
Stable 105691 (039634f)
BetterDiscord 1.3.0
Host 1.0.9003 Windows 10 64-Bit (10.0.18363)

**Additional Context**
 Nope

**Comment by ItzDShadow** [comment]
This issue is caused because `DiscordModules.Strings.COPY_ID` in createModal function is not defined, so the solution would be to replace it with your string (it would be displayed like on screenshot)
![screenshot](https://user-images.githubusercontent.com/62884000/145719954-075295e1-d7ae-4376-9dee-41c6622436eb.PNG)

**Comment by rauenzi** [comment]
This has been fixed in the latest version!
