### ISSUE TITLE
[Bug] BetterRoleColors not coloring user mentions

### ISSUE THREAD

**Issue by Kalaborative** [rauenzi/BetterDiscordAddons#615]
**Which plugin/theme is this about?**
BeterRoleColors

**Describe the Bug**
Not applying color to user mentions.

**To Reproduce**
Open Plugins, BetterRoleColors -> Settings, Toggle Mentions on
**Expected Behavior**
Username is colored whenever I mention them.

**Screenshots**
![image](https://user-images.githubusercontent.com/19222918/171084993-13634144-6580-494e-aee1-5db675514043.png)
Expected color to be light green, instead it's just white.

**Discord Version**
Stable

**Additional Context**
Some other features are bugged too such as not colorizing server username.

**Comment by MysticMismagius** [comment]
This has been happening to me as well. [Apparently it's been continuously popping up for some time now.](https://github.com/rauenzi/BetterDiscordAddons/issues/397)

I have tried:
* Checking the "Use Important" setting in the BetterRoleColors Plugin Settings
* Turning off all themes and other plugins to ensure that the issue was not an incompatibility with one of them
* Deleting and reinstalling the BetterRoleColors Plugin
* Deleting and reinstalling Better Discord
* Deleting and reinstalling Discord itself, then deleting and reinstalling Better Discord again

**Comment by rauenzi** [comment]
This should be fixed in the latest version!
