### ISSUE TITLE
Hiding Member List breaks plugin

### ISSUE THREAD

**Issue by GenesisAria** [rauenzi/BetterDiscordAddons#9]
Status stop working when member list is hidden using the button at the top.

**Comment by rauenzi** [comment]
Hey thanks for opening an issue! This is a known issue that I should have advertised a bit more.

For now, I'm not sure how to overcome this since that's where React stores all of the status data. The only way to overcome this is to constantly select the popout and it's data, however this method (previous method) is quite slow and laggy. If you want to try it out though, you can get that version here: https://github.com/rauenzi/BetterDiscordAddons/blob/91232fa9e4dfff0f5962fbf271f36ae532f3357b/Plugins/StatusEverywhere/StatusEverywhere.plugin.js

**Comment by rauenzi** [comment]
BRC now falls back to the previous method by collecting color data as much as it can. Will obviously be less reliable than with member list.

**Comment by GenesisAria** [comment]
This one was about status everywhere, not role colours haha.
